require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  TargetRailsVersion: 4.0
  Exclude:
    - 'activerecord-data_integrity.gemspec'
    - 'spec/support/*'
    - 'tmp/**/*'
    - 'gemfiles/*'
    - 'spec/internal/**/*'

Metrics/LineLength:
  Max: 110
