require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 4.0
  Exclude:
    - 'activerecord-data_integrity.gemspec'
    - 'spec/support/*'
    - 'tmp/**/*'
    - 'gemfiles/*'
    - 'spec/internal/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
   - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 3
