sudo: require
services:
- docker
install:
- gem install dip
before_script:
- unset BUNDLE_GEMFILE
- dip provision
script:
- dip rspec
- dip rubocop
deploy:
  provider: rubygems
  api_key:
    secure: Q3gyExePLXgWljK9mibX9A2AJR0GMjDJVMLYzJ4hu0vdc6+QwOTFcsDgqdhpqoOfrIBAVT5Hp+ry7slmwB8YzLMvRvM8tft7NjB2kpZE03uitDE9uYoYM9cKnguLDf3B5djLHcEy3T1ujD4wziEeU+SvVyyk/1jb1kSBRu2o4foDdveo8IB5m/DLBkz3YUYUVPd+SlyJPiVTitTRYIO5T2esENhNQHCEro1DVbXUC3e3KHuE38Nwpl6rcm54KCwp8Ji3f6135/XETxhPFRF9L5K6pLwAh6lqxEibspI9bYVOpVfNhqKvjqOY/zn+FHCgSAFIDKU1UQjAsBbYQMpIizL9gow0jQU4z87wM47wvFdZHOPtNEOivqIyiOccFxDT+X5qmqRmUY4FDi3wAqze3WXJkUadpoNPzZ78Xcl2ZVnPKbFMY2Omp7d0ghHkI31WGePKVT37S47vZZeCNPYgfMEWthNJK0Rch6nAGZBnolQoQKB/3n0ue0b3ik0pYgQkrZv/aG/3Dy5Od3aAzI84lRI78AzitiChxNZX+3c8hKtWZteBwHncdxTSeAXf9cZY9c9s7ssJGFoe7DOAWeAU84DhhbCsJ1UL87wOvserpVpaTXVs8tdsP5WSVNUucwl4CE7ewJBwFJMhELVAhzanyCmjFhjc8F2Za9Kpm/xQ7EM=
  gem: activerecord-data_integrity
  on:
    tags: true
    repo: dsalahutdinov/activerecord-data_integrity
