default: &default
  adapter: postgresql
  url: 'postgresql://postgres@127.0.0.1/amplifr_development'

development:
  <<: *default

test:
  <<: *default
  url: 'postgresql://postgres@127.0.0.1/amplifr_test'

production:
  <<: *default
