test:
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: <%= ENV.fetch("DB_NAME", "ar_di_test") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
