# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: 6.0.gemfile
            ruby: 2.7

          - gemfile: 6.0.gemfile
            ruby: 3.0

          - gemfile: 6.0.gemfile
            ruby: 3.1

          - gemfile: 6.1.gemfile
            ruby: 2.7

          - gemfile: 6.1.gemfile
            ruby: 3.0

          - gemfile: 6.1.gemfile
            ruby: 3.1

          - gemfile: 7.0.gemfile
            ruby: 2.7

          - gemfile: 7.0.gemfile
            ruby: 3.0

          - gemfile: 7.0.gemfile
            ruby: 3.1

    name: ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Bundle install
        run: |
          bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}"
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rspec
        env:
          DB_HOST: localhost
          DB_USERNAME: postgres
          DB_PORT: 5432
          DB_PASSWORD: postgres

      - name: Rubocop
        run: bundle exec rubocop
